### ISSUE TITLE
HaMLet S: exhaustiveness check for record ellipsis

### ISSUE THREAD

**Issue by minoki** [rossberg/hamlet#10]
The following program is (correctly) rejected because the pattern is non-exhaustive:

```sml
let val { a = SOME f } = { a = SOME (fn x => x) }
in f 1;
   f "x"
end;
```

But, a slight modification circumvents the exhaustiveness checker and allows the program to compile without a warning:

```sml
let val { ... = { a = SOME f } } = { a = SOME (fn x => x) }
in f 1;
   f "x"
end;
```

The exhaustiveness checker should correctly handle `...` pattern.

**Comment by rossberg** [comment]
Indeed, it seems like I never extended the exhaustiveness check to extensible records. Fixed now, thanks for reporting!
