### ISSUE TITLE
HaMLet homepage link broken

### ISSUE THREAD

**Issue by curiousleo** [rossberg/hamlet#2]
https://github.com/rossberg/hamlet/blob/master/doc/README.txt#L8 points to http://www.mpi-sws.org/hamlet/, which says "Page Not Found".

**Comment by rossberg-old** [comment]
Fixed, thanks!

**Comment by curiousleo** [comment]
Thank you! (For easier discoverability you could make http://www.mpi-sws.org/~rossberg/hamlet/ the "project link" of the Github project - this makes the link is show up more prominently.)
